# -*- mode: ruby -*-
# # vi: set ft=ruby :

# Specify minimum Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"

# Require YAML module
require 'yaml'

# Read YAML file with box details
servers = YAML.load_file('servers.yml')

numberOfServers = servers.length
currentMachine = 1
puts "Found Servers #{numberOfServers}"

# Create boxes
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Iterate through entries in YAML file
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
      srv.vm.network "private_network", ip: servers["ip"]
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
      end
      puts "Checking #{currentMachine} ==  #{numberOfServers}"
      if currentMachine == numberOfServers
        puts "Running Provisioning #{currentMachine} ==  #{numberOfServers}"
        config.vm.provision "ansible" do |ansible|
          ansible.limit = 'all'
          ansible.extra_vars = { user: "vagrant" }
          #ansible.inventory_path = "provisioning/hosts"
          ansible.playbook = "provisioning/node.yml"
        end
      end
      currentMachine = currentMachine + 1
    end
    # Only execute once the Ansible provisioner,
    # when all the machines are up and ready.

  end
end
