# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.ssh.forward_agent = true

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.111.71"

  #config.vm.network "forwarded_port", guest: 5432, host: 5442
  #config.vm.network "forwarded_port", guest: 8080, host: 8080
  #config.vm.network "forwarded_port", guest: 8090, host: 8090

  #syncs entire project directory to ~/application on target machine
  #config.vm.synced_folder "..", "/home/vagrant/apps", :nfs => true
  #config.vm.synced_folder "..", "/home/vagrant/apps"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", "1024"]
  end

  #provisions the environment
  config.vm.provision "ansible" do |ansible|
    ansible.limit = 'all'
    ansible.extra_vars = { user: "vagrant" }
    ansible.inventory_path = "provisioning/hosts"
    # ENV['PLAYBOOK']
    if ENV['PLAYBOOK'].nil?
      ansible.playbook = "provisioning/mean.yml"
    else
      ansible.playbook = "provisioning/" + ENV['PLAYBOOK'] + ".yml"
    end
  end
end
